FROM registry.access.redhat.com/ubi7/ubi:7.9

# Installing elfutils and rpm-build directly from centos7 repo since they are not available
# through any of the ubi7 repos
RUN yum update -y && \
    yum install -y python-setuptools \
                   make \
                   git \
                   rsync \
                   http://mirror.centos.org/centos/7/os/x86_64/Packages/elfutils-0.176-5.el7.x86_64.rpm \
                   http://mirror.centos.org/centos/7/updates/x86_64/Packages/rpm-build-4.11.3-48.el7_9.x86_64.rpm \
                   python-devel

# see ./Containerfile.ubi7 for explanation
RUN yum -y install python27-python-pip python2-requests && \
    scl enable python27 -- pip install -U --target /usr/lib/python2.7/site-packages/ pip==20.3.0 && \
    python -m pip install --ignore-installed pip==20.3.4 ipaddress

ENV PYTHON_VENV python2.7

COPY requirements.txt /tmp/requirements.txt

RUN pip install -U pip && \
	pip install --upgrade setuptools && \
	pip install --upgrade -r /tmp/requirements.txt
