FROM registry.access.redhat.com/ubi8/ubi:latest

RUN dnf update -y && \
    dnf install -y python3-setuptools python3-pip make git rsync findutils gcc python3-requests

ENV PYTHON_VENV python3.6

COPY requirements.txt /tmp/requirements.txt

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --upgrade setuptools && \
    python3 -m pip install --upgrade -r /tmp/requirements.txt
