name: PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run unit and component tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenarios:
        - name: Run tests on RHEL7
          distro: rhel7
        - name: Run tests on RHEL8
          distro: rhel8

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install strato-skipper
      - name: ${{matrix.scenarios.name}}
        run: |
          make pytest-${{matrix.scenarios.distro}}
